use_frameworks!

platform :ios, '10.0'

target 'GemvaryNetworkSDK_Example' do
  pod 'GemvaryNetworkSDK', :path => '../'

  target 'GemvaryNetworkSDK_Tests' do
    inherit! :search_paths

    
  end
end
